[tool.briefcase]
project_name = "To Do"
bundle = "ml.amarquaye"
version = "0.0.1"
url = "https://amarquaye.ml/todo"
license = "BSD license"
author = 'Jesse Amarquaye'
author_email = "llordjesse@gmial.com"

[tool.briefcase.app.todo]
formal_name = "To Do"
description = "A simple to do app written using beeware"
icon = "src/todo/resources/todo"
sources = ['src/todo']
requires = [
]


[tool.briefcase.app.todo.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.todo.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.todo.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.todo.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.todo.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.todo.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.todo.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.todo.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
